csharp4-lesson12/Models/Applicant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace csharp4_lesson12.Models
{
    public class Applicant
    {
        [Key]
        public int Id { get; set; }
        [Display(Name="First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }
        [Display(Name = "Age")]
        public int age { get; set; }
        [Display(Name = "Profession")]
        public string Profession { get; set; }
    }
}

csharp4-lesson12/Models/ApplicantContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration.Conventions;
using csharp4_lesson12.Models;

namespace csharp4_lesson12.Models
{
    public class ApplicantContext : DbContext
    {
        public DbSet<Applicant> applicants { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
    }
}

csharp4-lesson12/Models/ApplicantInitializer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using csharp4_lesson12.Models;
using csharp4_lesson12.Repositories;

namespace csharp4_lesson12.Models
{
    public class ApplicantInitializer : DropCreateDatabaseIfModelChanges<ApplicantContext>
    {
        protected override void Seed(ApplicantContext context)
        {
            var applicants = new List<Applicant>()
            {
                new Applicant{FirstName = "John", LastName="Doe", MiddleName="A", age=30},
                new Applicant{FirstName = "Jane", LastName="Doe", MiddleName="A", age=30},
            };
            applicants.ForEach(x=>context.applicants.Add(x));
            context.SaveChanges();
        }

    }
}

csharp4-lesson12/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using csharp4_lesson12.Repositories;
using csharp4_lesson12.Models;
using csharp4_lesson12.Interfaces;

namespace csharp4_lesson12.Controllers
{
    public class ApplicantController : Controller
    {
        private IApplicantsRepository ar;
        public ApplicantController()
        {
            ar = new ApplicantsRepository(new ApplicantContext());
        }

        public ApplicantController(IApplicantsRepository apprepo)
        {
            ar = apprepo;
        }
        public ActionResult Index()
        {
            var app = ar.GetAllApplicants();
            return View(app);
        }

        public ActionResult Search(string query="")
        {
            var app = ar.Search(query);
            return View("Index", app);
        }

        public ActionResult SearchByFirstName(string fn="")
        {
            if (!String.IsNullOrEmpty(fn))
            {
                var app = ar.SearchApplicantsByFirstName(x => x.FirstName.ToUpper() == fn.ToUpper());
                return View("Index", app);
            }
            else
            {
                var apps = ar.GetAllApplicants();
                return View("Index", apps);
            }
        }

        public ActionResult SearchByLastName(string ln = "")
        {
            if (!String.IsNullOrEmpty(ln))
            {
                var app = ar.SearchApplicantsByFirstName(x => x.LastName.ToUpper() == ln.ToUpper());
                return View("Index", app);
            }
            else
            {
                var apps = ar.GetAllApplicants();
                return View("Index", apps);
            }
        }

        public ActionResult SearchByMiddleName(string mid = "")
        {
            if (!String.IsNullOrEmpty(mid))
            {
                var app = ar.SearchApplicantsByFirstName(x => x.MiddleName.ToUpper() == mid.ToUpper());
                return View("Index", app);
            }
            else
            {
                var apps = ar.GetAllApplicants();
                return View("Index", apps);
            }
        }

        public ActionResult SearchByProfession(string pro = "")
        {
            if (!String.IsNullOrEmpty(pro))
            {
                var app = ar.SearchApplicantsByFirstName(x => x.Profession.ToUpper() == pro.ToUpper());
                return View("Index", app);
            }
            else
            {
                var apps = ar.GetAllApplicants();
                return View("Index", apps);
            }
        }

        public ActionResult OrderByFirstName()
        {
            ViewBag.sort = "firstname";
            return View(ar.OrderByFirstName());
        }

        public ActionResult OrderByLastName()
        {
            ViewBag.sort = "lastname";
            return View(ar.OrderByLastName());
        }

        public ActionResult OrderByMiddleName()
        {
            ViewBag.sort = "middlename";
            return View(ar.OrderByMiddleName());
        }


        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(Applicant app)
        {
            if (ModelState.IsValid)
            {
                ar.Create(app);
                ar.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(app);
        }

        public ActionResult Edit(int id=0)
        {
            Applicant app = ar.GetByApplicantNumber(id);
                if (app==null)
                {
                    return HttpNotFound();
                }
            return View(app);
        }

        [HttpPost]
        public ActionResult Edit(Applicant ap)
        {
            if (ModelState.IsValid)
            {
                ar.Edit(ap);
                ar.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ap);
        }

        public ActionResult Delete(int id=0)
        {
            Applicant app = ar.GetByApplicantNumber(id);
            if (app == null)
            {
                return HttpNotFound();
            }
            return View(app);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ar.Delete(id);
            ar.SaveChanges();
            return RedirectToAction("Index");
        }        

        protected override void Dispose(bool disposing)
        {
            ar.Dispose();
            base.Dispose(disposing);
        }

    }
}

csharp4-lesson12/Views/Applicant/Create.cshtml
@model csharp4_lesson12.Models.Applicant
@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Applicant</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.MiddleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MiddleName)
            @Html.ValidationMessageFor(model => model.MiddleName)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.age)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.age)
            @Html.ValidationMessageFor(model => model.age)
        </div>

           <div class="editor-label">
            @Html.LabelFor(model => model.Profession)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Profession)
            @Html.ValidationMessageFor(model => model.Profession)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

csharp4-lesson12/Views/Applicant/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

csharp4-lesson12/Views/Applicant/Edit.cshtml
@model csharp4_lesson12.Models.Applicant
@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>CdDb</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.MiddleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MiddleName)
            @Html.ValidationMessageFor(model => model.MiddleName)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.age)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.age)
            @Html.ValidationMessageFor(model => model.age)
        </div>
        
           <div class="editor-label">
            @Html.LabelFor(model => model.Profession)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Profession)
            @Html.ValidationMessageFor(model => model.Profession)
        </div>

        <p>
            <input type="submit" value="Edit" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

csharp4-lesson12/Views/Applicant/Index.cshtml
@model IEnumerable<csharp4_lesson12.Models.Applicant>
@{
    ViewBag.Title = "Applicants List";
}

<h2>Applicants</h2>
@using (Html.BeginForm("Search", "Applicant", FormMethod.Post)) 
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-field">
            @Html.TextBox("query", null, new { placeholder = "Search" })

        </div>
        <p>
            <input type="submit" value="Search" />
        </p>
    </fieldset>
}

@using (Html.BeginForm("SearchByFirstName", "Applicant", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-field">
            @Html.TextBox("fn", null, new { placeholder = "First Name Search" })

        </div>
        <p>
            <input type="submit" value="Search" />
        </p>
    </fieldset>
}

@using (Html.BeginForm("SearchByMiddleName", "Applicant", FormMethod.Post)) 
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-field">
            @Html.TextBox("mid", null, new { placeholder = "Middle Name Search" })

        </div>
        <p>
            <input type="submit" value="Search" />
        </p>
    </fieldset>
}

@using (Html.BeginForm("SearchByLastName", "Applicant", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-field">
            @Html.TextBox("ln", null, new { placeholder = "Last Name Search" })

        </div>
        <p>
            <input type="submit" value="Search" />
        </p>
    </fieldset>
}

@using (Html.BeginForm("SearchByProfession", "Applicant", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-field">
            @Html.TextBox("pro", null, new { placeholder = "Profession Search" })

        </div>
        <p>
            <input type="submit" value="Search" />
        </p>
    </fieldset>
}

<p>@Html.ActionLink("Create","Create","Applicant")</p>
<table>
<tr>
    <th>@Html.DisplayNameFor(model=>model.FirstName)</th>
    <th>@Html.DisplayNameFor(model=>model.MiddleName)</th>
    <th>@Html.DisplayNameFor(model=>model.LastName)</th>
    <th>@Html.DisplayNameFor(model=>model.age)</th>
    <th>@Html.DisplayNameFor(model=>model.Profession)</th>
</tr>

@foreach (var x in Model)
{
    <tr> 
        <td>@Html.DisplayFor(model => x.FirstName)</td>
        <td>@Html.DisplayFor(model => x.LastName)</td>
        <td>@Html.DisplayFor(model => x.LastName)</td>
        <td>@Html.DisplayFor(model => x.age)</td>
        <td>@Html.DisplayFor(model => x.Profession)</td>
    </tr>
}
</table>

csharp4-lesson12/Views/Applicant/OrderByFirstName.cshtml
@model IEnumerable<csharp4_lesson12.Models.Applicant>
@{
    ViewBag.Title = "Order By First Name";
}

<table>
<tr>
    <th>@Html.DisplayNameFor(model=>model.FirstName)</th>
    <th>@Html.DisplayNameFor(model=>model.MiddleName)</th>
    <th>@Html.DisplayNameFor(model=>model.LastName)</th>
    <th>@Html.DisplayNameFor(model=>model.age)</th>
    <th>@Html.DisplayNameFor(model=>model.Profession)</th>
</tr>
@foreach (var x in Model)
{
    <tr>
        <td class='highlight'>@Html.DisplayFor(model =>x.FirstName)</td>
        <td>@Html.DisplayFor(model =>x.MiddleName)</td>
        <td>@Html.DisplayFor(model =>x.LastName)</td>
        <td>@Html.DisplayFor(model =>x.age)</td>
        <td>@Html.DisplayFor(model =>x.Profession)</td>
    </tr>
}

</table>

csharp4-lesson12/Views/Applicant/OrderByLastName.cshtml
@model IEnumerable<csharp4_lesson12.Models.Applicant>
@{
    ViewBag.Title = "Order By Last Name";
}

<table>
<tr>
    <th>@Html.DisplayNameFor(model=>model.FirstName)</th>
    <th>@Html.DisplayNameFor(model=>model.MiddleName)</th>
    <th>@Html.DisplayNameFor(model=>model.LastName)</th>
    <th>@Html.DisplayNameFor(model=>model.age)</th>
    <th>@Html.DisplayNameFor(model=>model.Profession)</th>
</tr>
@foreach (var x in Model)
{
    <tr>
        <td>@Html.DisplayFor(model =>x.FirstName)</td>
        <td>@Html.DisplayFor(model =>x.MiddleName)</td>
        <td class='highlight'>@Html.DisplayFor(model =>x.LastName)</td>
        <td>@Html.DisplayFor(model =>x.age)</td>
        <td>@Html.DisplayFor(model =>x.Profession)</td>
    </tr>
}

</table>

csharp4-lesson12/Views/Applicant/OrderByMiddleName.cshtml
@model IEnumerable<csharp4_lesson12.Models.Applicant>
@{
    ViewBag.Title = "Order By Middle Name";
}
<table>
<tr>
    <th>@Html.DisplayNameFor(model=>model.FirstName)</th>
    <th>@Html.DisplayNameFor(model=>model.MiddleName)</th>
    <th>@Html.DisplayNameFor(model=>model.LastName)</th>
    <th>@Html.DisplayNameFor(model=>model.age)</th>
    <th>@Html.DisplayNameFor(model=>model.Profession)</th>
</tr>
@foreach (var x in Model)
{
    <tr>
        <td>@Html.DisplayFor(model =>x.FirstName)</td>
        <td class='highlight'>@Html.DisplayFor(model =>x.MiddleName)</td>
        <td>@Html.DisplayFor(model =>x.LastName)</td>
        <td>@Html.DisplayFor(model =>x.age)</td>
        <td>@Html.DisplayFor(model =>x.Profession)</td>
    </tr>
}

</table>

csharp4-lesson12/Views/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

csharp4-lesson12/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <style>
            .highlight {font-weight:bold}
        </style>
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Applicants Lists", "Index", "Applicant")</p>
                </div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Applicant")</li>
                            <li>@Html.SortActionLink("Sort by First Name", "OrderByFirstName", "Applicant")</li>
                            <li>@Html.SortActionLink("Sort by Middle Name", "OrderByMiddleName", "Applicant")</li>
                            <li>@Html.SortActionLink("Sort by Last Name", "OrderByLastName", "Applicant")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p></p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>